import type { ShallowRef } from 'vue'

import type { CharacterSourceDocument } from '../domains/characterSource'

import { inject, onScopeDispose, provide, shallowRef } from 'vue'

import { preprocessCharacterSource } from '../domains/characterSource'

/** Platform file failures safe for localization without a local path. */
export type CharacterSourceFileErrorCode
  = | 'file_changed_during_read'
    | 'file_too_large'
    | 'invalid_docx'
    | 'invalid_request'
    | 'invalid_utf8'
    | 'read_failed'
    | 'stat_failed'
    | 'unsupported_extension'

/** Sanitized platform payload accepted by the document session. */
export interface CharacterSourceSelectedFile {
  /** SHA-256 generated by the trusted local file adapter. */
  contentHash: string
  /** Strictly decoded UTF-8 text retained only for the active job. */
  content: string
  /** Basename without machine-local directories. */
  fileName: string
}

/** Request-scoped bridge implemented by Desktop or another platform. */
export interface CharacterSourceFileReader {
  /** Cancels native or filesystem work associated with the request. */
  cancel: (requestId: string) => Promise<void>
  /** Opens and reads one file without exposing its absolute path. */
  pick: (requestId: string) => Promise<
    | { status: 'cancelled' }
    | { error: CharacterSourceFileErrorCode, status: 'error' }
    | { file: CharacterSourceSelectedFile, status: 'selected' }
  >
}

/** Expected platform error raised before document preprocessing. */
export class CharacterSourceFileError extends Error {
  readonly code: CharacterSourceFileErrorCode

  constructor(code: CharacterSourceFileErrorCode) {
    super('Character source file selection failed.')
    this.name = 'CharacterSourceFileError'
    this.code = code
  }
}

/** Active in-memory document and cleanup operations for one import surface. */
export interface CharacterSourceDocumentSession {
  /** Current evidence document; cleared on cancellation, failure, or completion. */
  document: Readonly<ShallowRef<CharacterSourceDocument | undefined>>
  /** Cancels current work and clears all source blocks. */
  cancel: () => Promise<void>
  /** Clears source blocks after successful creation or explicit abandonment. */
  clear: () => void
  /** Selects and preprocesses one file while rejecting stale results. */
  select: () => Promise<CharacterSourceDocument | undefined>
}

const characterSourceFileReaderKey = Symbol('character-source-file-reader')

/** Provides the current platform's bounded source-file bridge. */
export function provideCharacterSourceFileReader(reader: CharacterSourceFileReader): void {
  provide(characterSourceFileReaderKey, reader)
}

/**
 * Creates one source-document lifecycle. A newer selection supersedes the
 * previous request, and no terminal path retains an unowned raw document.
 */
export function createCharacterSourceDocumentSession(
  reader: CharacterSourceFileReader,
  createRequestId: () => string = () => `source-${globalThis.crypto.randomUUID()}`,
): CharacterSourceDocumentSession {
  const document = shallowRef<CharacterSourceDocument>()
  let activeRequestId: string | undefined
  let generation = 0

  function clear(): void {
    document.value = undefined
  }

  async function cancel(): Promise<void> {
    generation++
    const requestId = activeRequestId
    activeRequestId = undefined
    clear()
    if (requestId)
      await reader.cancel(requestId)
  }

  async function select(): Promise<CharacterSourceDocument | undefined> {
    await cancel()
    const requestGeneration = generation
    const requestId = createRequestId()
    activeRequestId = requestId
    try {
      const result = await reader.pick(requestId)
      if (requestGeneration !== generation || activeRequestId !== requestId)
        return undefined
      if (result.status === 'cancelled')
        return undefined
      if (result.status === 'error')
        throw new CharacterSourceFileError(result.error)

      const nextDocument = preprocessCharacterSource({
        contentHash: result.file.contentHash,
        displayName: result.file.fileName,
        text: result.file.content,
      })
      document.value = nextDocument
      return nextDocument
    }
    catch (error) {
      clear()
      throw error
    }
    finally {
      if (activeRequestId === requestId)
        activeRequestId = undefined
    }
  }

  return { document, cancel, clear, select }
}

/** Creates a component-owned source session and disposes it on scope exit. */
export function useCharacterSourceDocumentSession(): CharacterSourceDocumentSession {
  const reader = inject<CharacterSourceFileReader>(characterSourceFileReaderKey)
  if (!reader)
    throw new Error('Character source file reader is not available on this platform.')
  const session = createCharacterSourceDocumentSession(reader)
  onScopeDispose(() => {
    void session.cancel()
  })
  return session
}
